development:
  adapter: mysql2
  encoding: utf8
  database: eightfoot_dev
  pool: 5
  username: root
  password:
  port: <%= ENV.fetch('BOXEN_MYSQL_PORT', 3306).to_i %>
  host: 127.0.0.1
  socket: /tmp/mysql.sock
  timeout: 5000

test:
  adapter: mysql2
  database: eightfoot_test
  username: root
  password:
  host: 127.0.0.1
  socket: /tmp/mysql_test.sock
  port: <%= ENV.fetch('BOXEN_MYSQL_PORT', 3306).to_i %>
  encoding: utf8
  pool: 5
  timeout: 5000

production:
  adapter: mysql2
  database: eightfoot
  username: root
  password:
  port: <%= ENV.fetch('BOXEN_MYSQL_PORT', 3306).to_i %>
  encoding: utf8
  pool: 5
  timeout: 5000
